public enum JSBridgeEventEnum: String, CaseIterable {
    case ping = "ping"
    case getProfile = "getProfile"
    case getDefaultAccount = "getDefaultAcc"
    case setBarTitle = "setBarTitle"
    case doPayment = "doPayment"
    case closeApp = "closeApp"
    case uploadFile = "uploadFile"
    case getConfig = "getConfig"
    case openMap = "openMap"
    case share = "share"
    case backToHome = "backToHomePage"
    case addCalendar = "addCalendar"
    case requestCurrentLocation = "requestCurrentLocation"
    case download = "download"
    case openApp = "openApp"
    case getNID = "getNID"
    case logError = "logError"
    case getFileDownload = "getFileDownload"
    case load = "load"
    case viewAppInfo = "viewAppInfo"
    case chooseAccount = "chooseAccount"
    case getStatus = "getStatus"
    case closePayment = "closePayment"
    case unknown = "unknown"
}
